version: '3.9'

services:
  articles-management-api-prod:
    container_name: articles-management-api-prod
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm run db-migrate && npm run start:prod"
    environment:
      NODE_ENV: production
      PORT: 3000

      DB_HOST: mysql
      DB_USER: test
      DB_PASSWORD: password
      DB_NAME: test_db
      DB_PORT: 3306

      SECRET_KEY: secret
      EXPIRATION_TIME: 25m
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306

volumes:
  mysql:
