version: '3.9'

services:
  articles-management-api-dev:
    container_name: articles-management-api-dev
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm run db-migrate && npm run start:dev"
    environment:
      NODE_ENV: development
      PORT: 3000

      SALT_VALUE: 10
      CACHE_DEFAULT_TIME: 600000 // 10 minutes
      SECRET_KEY: secret
      EXPIRATION_TIME: 25m

      DATABASE_URL_DEV: mysql://user:pass@mysql:3306/test_db

    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_DATABASE: test_db
    ports:
      - 3306:3306

volumes:
  mysql:
